### PR TITLE
Kill jsts

### PR DESCRIPTION
**Pull request by tcql**
This PR uses the [greiner-hormann](https://github.com/tchannel/greiner-hormann) algorithm that I've been working on implementing. It's considerably faster than JSTS, and removes our dependency on JSTS, aside from turf-buffer.

There are likely some quirks / edge case failures here, but we'll deal with those as they come up. Here's some known differences in the behavior:
- Intersect / Union / Difference no longer will return linestrings or points for cases where polygons touch at only an edge or a point (or several edges or points)
- Returned point orders may be different

### CODE REVIEW

**Comment by tchannel** [comment]
oh woops, messed up some of the comments / docblock. I'll fix it up.

**Comment by tchannel** [comment]
Note: I changed the tests and pulled in dev-dependency geojson-equality because point orders in results changed

**Comment by anandthakker** [comment]
@tchannel @morganherlocker Anything I could do to help this along?

**Comment by morganherlocker** [comment]
@anandthakker the one remaining JSTS dependency is for [polygon buffering](https://github.com/Turfjs/turf-buffer/pull/4).

**Comment by anandthakker** [comment]
@morganherlocker Oof

**Comment by tchannel** [comment]
@anandthakker I've also noticed a few bugs in the Greiner-Hormann implementation, which I've been chipping away at (tchannel/greiner-hormann#15, tchannel/greiner-hormann#14)

I also want to clean up, RE: tchannel/greiner-hormann#11

**Comment by DrColossos** [comment]
is there any progress on this? we would love to have this inside turf-intersect since JSTS bloats our build immensely.

**Comment by tcql** [comment]
@DenisCarriere the greiner-hormann has some pretty serious bugs that I found after putting this PR together. The package also hasn't been under development recently. I'd still love to circle back sometime and improve it, but for now this dependency murderquest is dead.

**Comment by DenisCarriere** [comment]
@tcql that's a shame... I'm very PRO removing `jsts`, however it's not going to be an easy task.

**Pull request closed without merging**
